### ISSUE TITLE
Composer updating without call in composer.local.json

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/Mermaid#45]
### Setup and configuration

- Mermaid version: 2.2.0
- MediaWiki version: 1.31.6
- PHP version: 7.2
- Database system (MySQL, PostgresQL, etc.) and version: 10.3.22-MariaDB

### Issue
It happend to me twice that an update of a MW installation where Mermaid was NOT installed, resulted in updating mermaid to 2.2.0:

```
composer update --no-dev --prefer-source -o
Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 2 updates, 0 removals
  - Updating mediawiki/mermaid (2.1.1 => 2.2.0): Loading from cache
  - Updating markbaker/complex (1.4.7 => 1.4.8): Downloading (100%)

```
How can it update mermaid from 2.1.1 to 2.2.2 if my composer.local.json looks like this:
```
        "require": {
                "mediawiki/semantic-media-wiki": "~3",
                "mediawiki/semantic-result-formats": "~3",
                "phpoffice/phpspreadsheet": "~1",
                "mediawiki/semantic-compound-queries": "~2",
                "mediawiki/semantic-extra-special-properties": "~2.0",
                "mediawiki/maps": "~7",
                "mediawiki/semantic-glossary": "~3",
                "professional-wiki/modern-timeline": "~1.0",
                "mediawiki/chameleon-skin": "~1",
                "mediawiki/simple-batch-upload": "~1.4"
```

Also, mermaid 2.2.2 is not compatible with MW 1.31 afaik, so it should say it needs at least MW 1.33...

**Comment by mwjames** [comment]
> Also, mermaid 2.2.2 is not compatible with MW 1.31 afaik, so it should say it needs at least MW 1.33...

Here applies the same comment as in https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/570#issuecomment-599029961.

**Comment by kghbln** [comment]
> It happend to me twice that an update of a MW installation where Mermaid was NOT installed, resulted in updating mermaid to 2.2.0:

> How can it update mermaid from 2.1.1 to 2.2.2 if my composer.local.json looks like this:

Mermaid was indeed installed before, since it was required via SRF.

In case you would like to avoid this you explicitly have to add `"mediawiki/mermaid": "2.1.0"` to your "composer.local.json" file.

> Also, mermaid 2.2.2 is not compatible with MW 1.31 afaik, so it should say it needs at least MW 1.33...

Well, MediaWiki complains about this. Still it will indeed be nicer if the software was not updated in the first place. Dunno if this can be done with Composer since MW itself is not installed via Composer.

Anyhow we now have a pull-request to make this situation better: https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/574 Thus closing here.
